document.write('<head>') 
document.write('<meta charset="utf-8">')
document.write('<meta http-equiv="X-UA-Compatible" content="IE=edge">')
document.write('<meta name="viewport" content="width=device-width, initial-scale=1">')
document.write('<title>Tomato</title>')
document.write('<link href="css/bootstrap.min.css" rel="stylesheet">')
document.write('<link href="style.css" rel="stylesheet">')
document.write('</head>')

document.write('<body>')
document.write('<div class="footer">')
document.write('<br>')
document.write('<div class="row">')
document.write('<div class="col-md-4"><strong>关于我们</strong></div>')
document.write('<div class="col-md-4"><strong>关于支付</strong></div>')
document.write('<div class="col-md-4"><strong>关于运费</strong></div>')
document.write('</div>')
document.write('<div class="row">')
document.write('<div style="font-size: 12px" class="col-md-4">番茄之家</div>')
document.write('<div style="font-size: 12px" class="col-md-4">全部为加拿大元</div>')
document.write('<div style="font-size: 12px" class="col-md-4">配送方式</div>')
document.write('</div>')
document.write('<div class="row">')
document.write('<div style="font-size: 12px" class="col-md-4">报告问题</div>')
document.write('<div style="font-size: 12px" class="col-md-4"></div>')
document.write('<div style="font-size: 12px" class="col-md-4">点击估算运费</div>')
document.write('</div>')

document.write('<br>')
document.write('<br>')

document.write('<div>')
document.write('<p>&copy; 2017 🍅番茄</p>')
document.write('</div>')
document.write('</div>')
document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>')
document.write('<script src="js/bootstrap.min.js"></script> ')
document.write('</body>')
