document.write('<head>') 
document.write('<meta charset="utf-8">')
document.write('<meta http-equiv="X-UA-Compatible" content="IE=edge">')
document.write('<meta name="viewport" content="width=device-width, initial-scale=1">')
document.write('<title>Tomato</title>')
document.write('<link href="css/bootstrap.min.css" rel="stylesheet">')
document.write('<link href="style.css" rel="stylesheet">')
document.write('</head>')

document.write('<body>')
document.write('<nav class="navbar navbar-inverse">')
document.write('<div class="container-fluid">')
document.write('<!-- Brand and toggle get grouped for better mobile display -->')
document.write('<div class="navbar-header">')
document.write('<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">')
document.write('<span class="sr-only">Toggle navigation</span>')
document.write('<span class="icon-bar"></span>')
document.write('<span class="icon-bar"></span>')
document.write('<span class="icon-bar"></span>')
document.write('</button>')
document.write('<ul class="nav navbar-nav">')
document.write('<li class="hidden-sm hidden-xs">')
document.write('<a href="#"><img src="../img/resize.png" alt=""></a>')
document.write('</li>')
document.write('</ul>')
document.write('</div>')
document.write('<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">')
document.write('<ul class="nav navbar-nav">')
document.write('<a class="navbar-brand" href="#">番茄日代网</a>')
document.write('<li class="active"><a href="../index.html">首页</a></li>')
document.write('<li class="dropdown">')
document.write('<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 彩妆护肤 <span class="caret"></span></a>')
document.write('<ul class="dropdown-menu">')
document.write('<li><a href="../foundation/index.html"> 底妆 </a></li>')
document.write('<li><a href="#">水乳</a></li>')
document.write('<li><a href="#">洗面奶</a></li>')
document.write('<li><a href="#">护肤防晒</a></li>')
document.write('</ul>')
document.write('</li>')
document.write('<li><a href="../mask/index.html">面膜</a></li>')
document.write('<li><a href="#">食品</a></li>')
document.write('<li><a href="#">cosme大赏好物</a></li>')
document.write('<li><a href="#">其他</a></li>')
document.write('</ul>')

document.write('<form class="navbar-form navbar-left">')
document.write('<div class="input-group">')
document.write('<input type="text" class="form-control" placeholder="Search">')
document.write('<div class="input-group-btn">')
document.write('<button class="btn btn-default" type="submit">')
document.write('<i class="glyphicon glyphicon-search"></i>')
document.write('</button>')
document.write('</div>')
document.write('</div>')
document.write('</form>')

document.write('<ul class="nav navbar-nav navbar-right">')
document.write('<li><a href="../Credit/index.html">积分墙</a></li>')
document.write('<li><a href="#">登录</a></li>')
document.write('<li class="dropdown">')
document.write('<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人中心 <span class="caret"></span></a>')
document.write('<ul class="dropdown-menu">')
document.write('<li><a href="#">我的账号</a></li>')
document.write('<li><a href="#">我的订单</a></li>')
document.write('<li><a href="#">我的收藏</a></li>')
document.write('<li><a href="#">退出登录</a></li>')
document.write('</ul>')
document.write('</li>')
document.write('</ul>')
document.write('</div><!-- /.navbar-collapse -->')
document.write('</div><!-- /.container-fluid -->')
document.write('</nav>')
document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>')
document.write('<script src="js/bootstrap.min.js"></script> ')
document.write('</body>')
